#############################################################################
# Makefile for building: SMART_Build
# Generated by qmake (3.0) (Qt 5.4.2)
# Project:  SMART_Build.pro
# Template: subdirs
# Command: C:\Qt\5.4\mingw491_32\bin\qmake.exe -spec win32-g++ CONFIG+=debug -o Makefile SMART_Build.pro
#############################################################################

MAKEFILE      = Makefile

first: make_first
QMAKE         = C:\Qt\5.4\mingw491_32\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = $(COPY)
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = del
SYMLINK       = copy /y
DEL_DIR       = rmdir
MOVE          = move
SUBTARGETS    =  \
		sub-PCC \
		sub-Flasher \
		sub-BRS \
		sub-Emokit \
		sub-BCI


sub-PCC-qmake_all:  FORCE
	@if not exist PCC\ mkdir PCC\ & if not exist PCC\ exit 1
	cd PCC\ && $(QMAKE) C:\Qt\workspace\SMART_Software\SMART_Build\PCC\PCC.pro -spec win32-g++ CONFIG+=debug -o Makefile
	cd PCC\ && $(MAKE) -f Makefile qmake_all
sub-PCC: FORCE
	@if not exist PCC\ mkdir PCC\ & if not exist PCC\ exit 1
	cd PCC\ && ( if not exist Makefile $(QMAKE) C:\Qt\workspace\SMART_Software\SMART_Build\PCC\PCC.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile
sub-PCC-make_first: FORCE
	@if not exist PCC\ mkdir PCC\ & if not exist PCC\ exit 1
	cd PCC\ && ( if not exist Makefile $(QMAKE) C:\Qt\workspace\SMART_Software\SMART_Build\PCC\PCC.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile 
sub-PCC-all: FORCE
	@if not exist PCC\ mkdir PCC\ & if not exist PCC\ exit 1
	cd PCC\ && ( if not exist Makefile $(QMAKE) C:\Qt\workspace\SMART_Software\SMART_Build\PCC\PCC.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile all
sub-PCC-clean: FORCE
	@if not exist PCC\ mkdir PCC\ & if not exist PCC\ exit 1
	cd PCC\ && ( if not exist Makefile $(QMAKE) C:\Qt\workspace\SMART_Software\SMART_Build\PCC\PCC.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-PCC-distclean: FORCE
	@if not exist PCC\ mkdir PCC\ & if not exist PCC\ exit 1
	cd PCC\ && ( if not exist Makefile $(QMAKE) C:\Qt\workspace\SMART_Software\SMART_Build\PCC\PCC.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-PCC-install_subtargets: FORCE
	@if not exist PCC\ mkdir PCC\ & if not exist PCC\ exit 1
	cd PCC\ && ( if not exist Makefile $(QMAKE) C:\Qt\workspace\SMART_Software\SMART_Build\PCC\PCC.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile install
sub-PCC-uninstall_subtargets: FORCE
	@if not exist PCC\ mkdir PCC\ & if not exist PCC\ exit 1
	cd PCC\ && ( if not exist Makefile $(QMAKE) C:\Qt\workspace\SMART_Software\SMART_Build\PCC\PCC.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-Flasher-qmake_all:  FORCE
	@if not exist Flasher\ mkdir Flasher\ & if not exist Flasher\ exit 1
	cd Flasher\ && $(QMAKE) C:\Qt\workspace\SMART_Software\SMART_Build\Flasher\Flasher.pro -spec win32-g++ CONFIG+=debug -o Makefile
	cd Flasher\ && $(MAKE) -f Makefile qmake_all
sub-Flasher: FORCE
	@if not exist Flasher\ mkdir Flasher\ & if not exist Flasher\ exit 1
	cd Flasher\ && ( if not exist Makefile $(QMAKE) C:\Qt\workspace\SMART_Software\SMART_Build\Flasher\Flasher.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile
sub-Flasher-make_first: FORCE
	@if not exist Flasher\ mkdir Flasher\ & if not exist Flasher\ exit 1
	cd Flasher\ && ( if not exist Makefile $(QMAKE) C:\Qt\workspace\SMART_Software\SMART_Build\Flasher\Flasher.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile 
sub-Flasher-all: FORCE
	@if not exist Flasher\ mkdir Flasher\ & if not exist Flasher\ exit 1
	cd Flasher\ && ( if not exist Makefile $(QMAKE) C:\Qt\workspace\SMART_Software\SMART_Build\Flasher\Flasher.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile all
sub-Flasher-clean: FORCE
	@if not exist Flasher\ mkdir Flasher\ & if not exist Flasher\ exit 1
	cd Flasher\ && ( if not exist Makefile $(QMAKE) C:\Qt\workspace\SMART_Software\SMART_Build\Flasher\Flasher.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-Flasher-distclean: FORCE
	@if not exist Flasher\ mkdir Flasher\ & if not exist Flasher\ exit 1
	cd Flasher\ && ( if not exist Makefile $(QMAKE) C:\Qt\workspace\SMART_Software\SMART_Build\Flasher\Flasher.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-Flasher-install_subtargets: FORCE
	@if not exist Flasher\ mkdir Flasher\ & if not exist Flasher\ exit 1
	cd Flasher\ && ( if not exist Makefile $(QMAKE) C:\Qt\workspace\SMART_Software\SMART_Build\Flasher\Flasher.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile install
sub-Flasher-uninstall_subtargets: FORCE
	@if not exist Flasher\ mkdir Flasher\ & if not exist Flasher\ exit 1
	cd Flasher\ && ( if not exist Makefile $(QMAKE) C:\Qt\workspace\SMART_Software\SMART_Build\Flasher\Flasher.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-BRS-qmake_all:  FORCE
	@if not exist BRS\ mkdir BRS\ & if not exist BRS\ exit 1
	cd BRS\ && $(QMAKE) C:\Qt\workspace\SMART_Software\SMART_Build\BRS\BRS.pro -spec win32-g++ CONFIG+=debug -o Makefile
	cd BRS\ && $(MAKE) -f Makefile qmake_all
sub-BRS: FORCE
	@if not exist BRS\ mkdir BRS\ & if not exist BRS\ exit 1
	cd BRS\ && ( if not exist Makefile $(QMAKE) C:\Qt\workspace\SMART_Software\SMART_Build\BRS\BRS.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile
sub-BRS-make_first: FORCE
	@if not exist BRS\ mkdir BRS\ & if not exist BRS\ exit 1
	cd BRS\ && ( if not exist Makefile $(QMAKE) C:\Qt\workspace\SMART_Software\SMART_Build\BRS\BRS.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile 
sub-BRS-all: FORCE
	@if not exist BRS\ mkdir BRS\ & if not exist BRS\ exit 1
	cd BRS\ && ( if not exist Makefile $(QMAKE) C:\Qt\workspace\SMART_Software\SMART_Build\BRS\BRS.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile all
sub-BRS-clean: FORCE
	@if not exist BRS\ mkdir BRS\ & if not exist BRS\ exit 1
	cd BRS\ && ( if not exist Makefile $(QMAKE) C:\Qt\workspace\SMART_Software\SMART_Build\BRS\BRS.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-BRS-distclean: FORCE
	@if not exist BRS\ mkdir BRS\ & if not exist BRS\ exit 1
	cd BRS\ && ( if not exist Makefile $(QMAKE) C:\Qt\workspace\SMART_Software\SMART_Build\BRS\BRS.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-BRS-install_subtargets: FORCE
	@if not exist BRS\ mkdir BRS\ & if not exist BRS\ exit 1
	cd BRS\ && ( if not exist Makefile $(QMAKE) C:\Qt\workspace\SMART_Software\SMART_Build\BRS\BRS.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile install
sub-BRS-uninstall_subtargets: FORCE
	@if not exist BRS\ mkdir BRS\ & if not exist BRS\ exit 1
	cd BRS\ && ( if not exist Makefile $(QMAKE) C:\Qt\workspace\SMART_Software\SMART_Build\BRS\BRS.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-Emokit-qmake_all:  FORCE
	@if not exist Emokit\ mkdir Emokit\ & if not exist Emokit\ exit 1
	cd Emokit\ && $(QMAKE) C:\Qt\workspace\SMART_Software\SMART_Build\Emokit\Emokit.pro -spec win32-g++ CONFIG+=debug -o Makefile
	cd Emokit\ && $(MAKE) -f Makefile qmake_all
sub-Emokit: FORCE
	@if not exist Emokit\ mkdir Emokit\ & if not exist Emokit\ exit 1
	cd Emokit\ && ( if not exist Makefile $(QMAKE) C:\Qt\workspace\SMART_Software\SMART_Build\Emokit\Emokit.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile
sub-Emokit-make_first: FORCE
	@if not exist Emokit\ mkdir Emokit\ & if not exist Emokit\ exit 1
	cd Emokit\ && ( if not exist Makefile $(QMAKE) C:\Qt\workspace\SMART_Software\SMART_Build\Emokit\Emokit.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile 
sub-Emokit-all: FORCE
	@if not exist Emokit\ mkdir Emokit\ & if not exist Emokit\ exit 1
	cd Emokit\ && ( if not exist Makefile $(QMAKE) C:\Qt\workspace\SMART_Software\SMART_Build\Emokit\Emokit.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile all
sub-Emokit-clean: FORCE
	@if not exist Emokit\ mkdir Emokit\ & if not exist Emokit\ exit 1
	cd Emokit\ && ( if not exist Makefile $(QMAKE) C:\Qt\workspace\SMART_Software\SMART_Build\Emokit\Emokit.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-Emokit-distclean: FORCE
	@if not exist Emokit\ mkdir Emokit\ & if not exist Emokit\ exit 1
	cd Emokit\ && ( if not exist Makefile $(QMAKE) C:\Qt\workspace\SMART_Software\SMART_Build\Emokit\Emokit.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-Emokit-install_subtargets: FORCE
	@if not exist Emokit\ mkdir Emokit\ & if not exist Emokit\ exit 1
	cd Emokit\ && ( if not exist Makefile $(QMAKE) C:\Qt\workspace\SMART_Software\SMART_Build\Emokit\Emokit.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile install
sub-Emokit-uninstall_subtargets: FORCE
	@if not exist Emokit\ mkdir Emokit\ & if not exist Emokit\ exit 1
	cd Emokit\ && ( if not exist Makefile $(QMAKE) C:\Qt\workspace\SMART_Software\SMART_Build\Emokit\Emokit.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile uninstall
sub-BCI-qmake_all:  FORCE
	@if not exist BCI\ mkdir BCI\ & if not exist BCI\ exit 1
	cd BCI\ && $(QMAKE) C:\Qt\workspace\SMART_Software\SMART_Build\BCI\BCI.pro -spec win32-g++ CONFIG+=debug -o Makefile
	cd BCI\ && $(MAKE) -f Makefile qmake_all
sub-BCI: FORCE
	@if not exist BCI\ mkdir BCI\ & if not exist BCI\ exit 1
	cd BCI\ && ( if not exist Makefile $(QMAKE) C:\Qt\workspace\SMART_Software\SMART_Build\BCI\BCI.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile
sub-BCI-make_first: FORCE
	@if not exist BCI\ mkdir BCI\ & if not exist BCI\ exit 1
	cd BCI\ && ( if not exist Makefile $(QMAKE) C:\Qt\workspace\SMART_Software\SMART_Build\BCI\BCI.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile 
sub-BCI-all: FORCE
	@if not exist BCI\ mkdir BCI\ & if not exist BCI\ exit 1
	cd BCI\ && ( if not exist Makefile $(QMAKE) C:\Qt\workspace\SMART_Software\SMART_Build\BCI\BCI.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile all
sub-BCI-clean: FORCE
	@if not exist BCI\ mkdir BCI\ & if not exist BCI\ exit 1
	cd BCI\ && ( if not exist Makefile $(QMAKE) C:\Qt\workspace\SMART_Software\SMART_Build\BCI\BCI.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile clean
sub-BCI-distclean: FORCE
	@if not exist BCI\ mkdir BCI\ & if not exist BCI\ exit 1
	cd BCI\ && ( if not exist Makefile $(QMAKE) C:\Qt\workspace\SMART_Software\SMART_Build\BCI\BCI.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile distclean
sub-BCI-install_subtargets: FORCE
	@if not exist BCI\ mkdir BCI\ & if not exist BCI\ exit 1
	cd BCI\ && ( if not exist Makefile $(QMAKE) C:\Qt\workspace\SMART_Software\SMART_Build\BCI\BCI.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile install
sub-BCI-uninstall_subtargets: FORCE
	@if not exist BCI\ mkdir BCI\ & if not exist BCI\ exit 1
	cd BCI\ && ( if not exist Makefile $(QMAKE) C:\Qt\workspace\SMART_Software\SMART_Build\BCI\BCI.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile uninstall

Makefile: SMART_Build.pro ../../../5.4/mingw491_32/mkspecs/win32-g++/qmake.conf ../../../5.4/mingw491_32/mkspecs/features/spec_pre.prf \
		../../../5.4/mingw491_32/mkspecs/qdevice.pri \
		../../../5.4/mingw491_32/mkspecs/features/device_config.prf \
		../../../5.4/mingw491_32/mkspecs/common/shell-win32.conf \
		../../../5.4/mingw491_32/mkspecs/qconfig.pri \
		../../../5.4/mingw491_32/mkspecs/modules/qt_lib_axbase.pri \
		../../../5.4/mingw491_32/mkspecs/modules/qt_lib_axbase_private.pri \
		../../../5.4/mingw491_32/mkspecs/modules/qt_lib_axcontainer.pri \
		../../../5.4/mingw491_32/mkspecs/modules/qt_lib_axcontainer_private.pri \
		../../../5.4/mingw491_32/mkspecs/modules/qt_lib_axserver.pri \
		../../../5.4/mingw491_32/mkspecs/modules/qt_lib_axserver_private.pri \
		../../../5.4/mingw491_32/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../5.4/mingw491_32/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../5.4/mingw491_32/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../5.4/mingw491_32/mkspecs/modules/qt_lib_clucene_private.pri \
		../../../5.4/mingw491_32/mkspecs/modules/qt_lib_concurrent.pri \
		../../../5.4/mingw491_32/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../5.4/mingw491_32/mkspecs/modules/qt_lib_core.pri \
		../../../5.4/mingw491_32/mkspecs/modules/qt_lib_core_private.pri \
		../../../5.4/mingw491_32/mkspecs/modules/qt_lib_dbus.pri \
		../../../5.4/mingw491_32/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../5.4/mingw491_32/mkspecs/modules/qt_lib_declarative.pri \
		../../../5.4/mingw491_32/mkspecs/modules/qt_lib_declarative_private.pri \
		../../../5.4/mingw491_32/mkspecs/modules/qt_lib_designer.pri \
		../../../5.4/mingw491_32/mkspecs/modules/qt_lib_designer_private.pri \
		../../../5.4/mingw491_32/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../5.4/mingw491_32/mkspecs/modules/qt_lib_enginio.pri \
		../../../5.4/mingw491_32/mkspecs/modules/qt_lib_enginio_private.pri \
		../../../5.4/mingw491_32/mkspecs/modules/qt_lib_gui.pri \
		../../../5.4/mingw491_32/mkspecs/modules/qt_lib_gui_private.pri \
		../../../5.4/mingw491_32/mkspecs/modules/qt_lib_help.pri \
		../../../5.4/mingw491_32/mkspecs/modules/qt_lib_help_private.pri \
		../../../5.4/mingw491_32/mkspecs/modules/qt_lib_location.pri \
		../../../5.4/mingw491_32/mkspecs/modules/qt_lib_location_private.pri \
		../../../5.4/mingw491_32/mkspecs/modules/qt_lib_multimedia.pri \
		../../../5.4/mingw491_32/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../5.4/mingw491_32/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../5.4/mingw491_32/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../5.4/mingw491_32/mkspecs/modules/qt_lib_network.pri \
		../../../5.4/mingw491_32/mkspecs/modules/qt_lib_network_private.pri \
		../../../5.4/mingw491_32/mkspecs/modules/qt_lib_nfc.pri \
		../../../5.4/mingw491_32/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../5.4/mingw491_32/mkspecs/modules/qt_lib_opengl.pri \
		../../../5.4/mingw491_32/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../5.4/mingw491_32/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../5.4/mingw491_32/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../5.4/mingw491_32/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../../5.4/mingw491_32/mkspecs/modules/qt_lib_positioning.pri \
		../../../5.4/mingw491_32/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../5.4/mingw491_32/mkspecs/modules/qt_lib_printsupport.pri \
		../../../5.4/mingw491_32/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../5.4/mingw491_32/mkspecs/modules/qt_lib_qml.pri \
		../../../5.4/mingw491_32/mkspecs/modules/qt_lib_qml_private.pri \
		../../../5.4/mingw491_32/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../5.4/mingw491_32/mkspecs/modules/qt_lib_qmltest.pri \
		../../../5.4/mingw491_32/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../5.4/mingw491_32/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../5.4/mingw491_32/mkspecs/modules/qt_lib_quick.pri \
		../../../5.4/mingw491_32/mkspecs/modules/qt_lib_quick_private.pri \
		../../../5.4/mingw491_32/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../5.4/mingw491_32/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../5.4/mingw491_32/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../5.4/mingw491_32/mkspecs/modules/qt_lib_script.pri \
		../../../5.4/mingw491_32/mkspecs/modules/qt_lib_script_private.pri \
		../../../5.4/mingw491_32/mkspecs/modules/qt_lib_scripttools.pri \
		../../../5.4/mingw491_32/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../5.4/mingw491_32/mkspecs/modules/qt_lib_sensors.pri \
		../../../5.4/mingw491_32/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../5.4/mingw491_32/mkspecs/modules/qt_lib_serialport.pri \
		../../../5.4/mingw491_32/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../5.4/mingw491_32/mkspecs/modules/qt_lib_sql.pri \
		../../../5.4/mingw491_32/mkspecs/modules/qt_lib_sql_private.pri \
		../../../5.4/mingw491_32/mkspecs/modules/qt_lib_svg.pri \
		../../../5.4/mingw491_32/mkspecs/modules/qt_lib_svg_private.pri \
		../../../5.4/mingw491_32/mkspecs/modules/qt_lib_testlib.pri \
		../../../5.4/mingw491_32/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../5.4/mingw491_32/mkspecs/modules/qt_lib_uitools.pri \
		../../../5.4/mingw491_32/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../5.4/mingw491_32/mkspecs/modules/qt_lib_webchannel.pri \
		../../../5.4/mingw491_32/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../5.4/mingw491_32/mkspecs/modules/qt_lib_webkit.pri \
		../../../5.4/mingw491_32/mkspecs/modules/qt_lib_webkit_private.pri \
		../../../5.4/mingw491_32/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../../5.4/mingw491_32/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../../5.4/mingw491_32/mkspecs/modules/qt_lib_websockets.pri \
		../../../5.4/mingw491_32/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../5.4/mingw491_32/mkspecs/modules/qt_lib_webview.pri \
		../../../5.4/mingw491_32/mkspecs/modules/qt_lib_webview_private.pri \
		../../../5.4/mingw491_32/mkspecs/modules/qt_lib_widgets.pri \
		../../../5.4/mingw491_32/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../5.4/mingw491_32/mkspecs/modules/qt_lib_winextras.pri \
		../../../5.4/mingw491_32/mkspecs/modules/qt_lib_winextras_private.pri \
		../../../5.4/mingw491_32/mkspecs/modules/qt_lib_xml.pri \
		../../../5.4/mingw491_32/mkspecs/modules/qt_lib_xml_private.pri \
		../../../5.4/mingw491_32/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../5.4/mingw491_32/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../5.4/mingw491_32/mkspecs/features/qt_functions.prf \
		../../../5.4/mingw491_32/mkspecs/features/qt_config.prf \
		../../../5.4/mingw491_32/mkspecs/features/win32/qt_config.prf \
		../../../5.4/mingw491_32/mkspecs/win32-g++/qmake.conf \
		../../../5.4/mingw491_32/mkspecs/features/spec_post.prf \
		../../../5.4/mingw491_32/mkspecs/features/exclusive_builds.prf \
		../../../5.4/mingw491_32/mkspecs/features/default_pre.prf \
		../../../5.4/mingw491_32/mkspecs/features/win32/default_pre.prf \
		../../../5.4/mingw491_32/mkspecs/features/resolve_config.prf \
		../../../5.4/mingw491_32/mkspecs/features/exclusive_builds_post.prf \
		../../../5.4/mingw491_32/mkspecs/features/default_post.prf \
		../../../5.4/mingw491_32/mkspecs/features/win32/rtti.prf \
		../../../5.4/mingw491_32/mkspecs/features/precompile_header.prf \
		../../../5.4/mingw491_32/mkspecs/features/warn_on.prf \
		../../../5.4/mingw491_32/mkspecs/features/win32/windows.prf \
		../../../5.4/mingw491_32/mkspecs/features/testcase_targets.prf \
		../../../5.4/mingw491_32/mkspecs/features/exceptions.prf \
		../../../5.4/mingw491_32/mkspecs/features/yacc.prf \
		../../../5.4/mingw491_32/mkspecs/features/lex.prf \
		SMART_Build.pro
	$(QMAKE) -spec win32-g++ CONFIG+=debug -o Makefile SMART_Build.pro
..\..\..\5.4\mingw491_32\mkspecs\features\spec_pre.prf:
..\..\..\5.4\mingw491_32\mkspecs\qdevice.pri:
..\..\..\5.4\mingw491_32\mkspecs\features\device_config.prf:
..\..\..\5.4\mingw491_32\mkspecs\common\shell-win32.conf:
..\..\..\5.4\mingw491_32\mkspecs\qconfig.pri:
..\..\..\5.4\mingw491_32\mkspecs\modules\qt_lib_axbase.pri:
..\..\..\5.4\mingw491_32\mkspecs\modules\qt_lib_axbase_private.pri:
..\..\..\5.4\mingw491_32\mkspecs\modules\qt_lib_axcontainer.pri:
..\..\..\5.4\mingw491_32\mkspecs\modules\qt_lib_axcontainer_private.pri:
..\..\..\5.4\mingw491_32\mkspecs\modules\qt_lib_axserver.pri:
..\..\..\5.4\mingw491_32\mkspecs\modules\qt_lib_axserver_private.pri:
..\..\..\5.4\mingw491_32\mkspecs\modules\qt_lib_bluetooth.pri:
..\..\..\5.4\mingw491_32\mkspecs\modules\qt_lib_bluetooth_private.pri:
..\..\..\5.4\mingw491_32\mkspecs\modules\qt_lib_bootstrap_private.pri:
..\..\..\5.4\mingw491_32\mkspecs\modules\qt_lib_clucene_private.pri:
..\..\..\5.4\mingw491_32\mkspecs\modules\qt_lib_concurrent.pri:
..\..\..\5.4\mingw491_32\mkspecs\modules\qt_lib_concurrent_private.pri:
..\..\..\5.4\mingw491_32\mkspecs\modules\qt_lib_core.pri:
..\..\..\5.4\mingw491_32\mkspecs\modules\qt_lib_core_private.pri:
..\..\..\5.4\mingw491_32\mkspecs\modules\qt_lib_dbus.pri:
..\..\..\5.4\mingw491_32\mkspecs\modules\qt_lib_dbus_private.pri:
..\..\..\5.4\mingw491_32\mkspecs\modules\qt_lib_declarative.pri:
..\..\..\5.4\mingw491_32\mkspecs\modules\qt_lib_declarative_private.pri:
..\..\..\5.4\mingw491_32\mkspecs\modules\qt_lib_designer.pri:
..\..\..\5.4\mingw491_32\mkspecs\modules\qt_lib_designer_private.pri:
..\..\..\5.4\mingw491_32\mkspecs\modules\qt_lib_designercomponents_private.pri:
..\..\..\5.4\mingw491_32\mkspecs\modules\qt_lib_enginio.pri:
..\..\..\5.4\mingw491_32\mkspecs\modules\qt_lib_enginio_private.pri:
..\..\..\5.4\mingw491_32\mkspecs\modules\qt_lib_gui.pri:
..\..\..\5.4\mingw491_32\mkspecs\modules\qt_lib_gui_private.pri:
..\..\..\5.4\mingw491_32\mkspecs\modules\qt_lib_help.pri:
..\..\..\5.4\mingw491_32\mkspecs\modules\qt_lib_help_private.pri:
..\..\..\5.4\mingw491_32\mkspecs\modules\qt_lib_location.pri:
..\..\..\5.4\mingw491_32\mkspecs\modules\qt_lib_location_private.pri:
..\..\..\5.4\mingw491_32\mkspecs\modules\qt_lib_multimedia.pri:
..\..\..\5.4\mingw491_32\mkspecs\modules\qt_lib_multimedia_private.pri:
..\..\..\5.4\mingw491_32\mkspecs\modules\qt_lib_multimediawidgets.pri:
..\..\..\5.4\mingw491_32\mkspecs\modules\qt_lib_multimediawidgets_private.pri:
..\..\..\5.4\mingw491_32\mkspecs\modules\qt_lib_network.pri:
..\..\..\5.4\mingw491_32\mkspecs\modules\qt_lib_network_private.pri:
..\..\..\5.4\mingw491_32\mkspecs\modules\qt_lib_nfc.pri:
..\..\..\5.4\mingw491_32\mkspecs\modules\qt_lib_nfc_private.pri:
..\..\..\5.4\mingw491_32\mkspecs\modules\qt_lib_opengl.pri:
..\..\..\5.4\mingw491_32\mkspecs\modules\qt_lib_opengl_private.pri:
..\..\..\5.4\mingw491_32\mkspecs\modules\qt_lib_openglextensions.pri:
..\..\..\5.4\mingw491_32\mkspecs\modules\qt_lib_openglextensions_private.pri:
..\..\..\5.4\mingw491_32\mkspecs\modules\qt_lib_platformsupport_private.pri:
..\..\..\5.4\mingw491_32\mkspecs\modules\qt_lib_positioning.pri:
..\..\..\5.4\mingw491_32\mkspecs\modules\qt_lib_positioning_private.pri:
..\..\..\5.4\mingw491_32\mkspecs\modules\qt_lib_printsupport.pri:
..\..\..\5.4\mingw491_32\mkspecs\modules\qt_lib_printsupport_private.pri:
..\..\..\5.4\mingw491_32\mkspecs\modules\qt_lib_qml.pri:
..\..\..\5.4\mingw491_32\mkspecs\modules\qt_lib_qml_private.pri:
..\..\..\5.4\mingw491_32\mkspecs\modules\qt_lib_qmldevtools_private.pri:
..\..\..\5.4\mingw491_32\mkspecs\modules\qt_lib_qmltest.pri:
..\..\..\5.4\mingw491_32\mkspecs\modules\qt_lib_qmltest_private.pri:
..\..\..\5.4\mingw491_32\mkspecs\modules\qt_lib_qtmultimediaquicktools_private.pri:
..\..\..\5.4\mingw491_32\mkspecs\modules\qt_lib_quick.pri:
..\..\..\5.4\mingw491_32\mkspecs\modules\qt_lib_quick_private.pri:
..\..\..\5.4\mingw491_32\mkspecs\modules\qt_lib_quickparticles_private.pri:
..\..\..\5.4\mingw491_32\mkspecs\modules\qt_lib_quickwidgets.pri:
..\..\..\5.4\mingw491_32\mkspecs\modules\qt_lib_quickwidgets_private.pri:
..\..\..\5.4\mingw491_32\mkspecs\modules\qt_lib_script.pri:
..\..\..\5.4\mingw491_32\mkspecs\modules\qt_lib_script_private.pri:
..\..\..\5.4\mingw491_32\mkspecs\modules\qt_lib_scripttools.pri:
..\..\..\5.4\mingw491_32\mkspecs\modules\qt_lib_scripttools_private.pri:
..\..\..\5.4\mingw491_32\mkspecs\modules\qt_lib_sensors.pri:
..\..\..\5.4\mingw491_32\mkspecs\modules\qt_lib_sensors_private.pri:
..\..\..\5.4\mingw491_32\mkspecs\modules\qt_lib_serialport.pri:
..\..\..\5.4\mingw491_32\mkspecs\modules\qt_lib_serialport_private.pri:
..\..\..\5.4\mingw491_32\mkspecs\modules\qt_lib_sql.pri:
..\..\..\5.4\mingw491_32\mkspecs\modules\qt_lib_sql_private.pri:
..\..\..\5.4\mingw491_32\mkspecs\modules\qt_lib_svg.pri:
..\..\..\5.4\mingw491_32\mkspecs\modules\qt_lib_svg_private.pri:
..\..\..\5.4\mingw491_32\mkspecs\modules\qt_lib_testlib.pri:
..\..\..\5.4\mingw491_32\mkspecs\modules\qt_lib_testlib_private.pri:
..\..\..\5.4\mingw491_32\mkspecs\modules\qt_lib_uitools.pri:
..\..\..\5.4\mingw491_32\mkspecs\modules\qt_lib_uitools_private.pri:
..\..\..\5.4\mingw491_32\mkspecs\modules\qt_lib_webchannel.pri:
..\..\..\5.4\mingw491_32\mkspecs\modules\qt_lib_webchannel_private.pri:
..\..\..\5.4\mingw491_32\mkspecs\modules\qt_lib_webkit.pri:
..\..\..\5.4\mingw491_32\mkspecs\modules\qt_lib_webkit_private.pri:
..\..\..\5.4\mingw491_32\mkspecs\modules\qt_lib_webkitwidgets.pri:
..\..\..\5.4\mingw491_32\mkspecs\modules\qt_lib_webkitwidgets_private.pri:
..\..\..\5.4\mingw491_32\mkspecs\modules\qt_lib_websockets.pri:
..\..\..\5.4\mingw491_32\mkspecs\modules\qt_lib_websockets_private.pri:
..\..\..\5.4\mingw491_32\mkspecs\modules\qt_lib_webview.pri:
..\..\..\5.4\mingw491_32\mkspecs\modules\qt_lib_webview_private.pri:
..\..\..\5.4\mingw491_32\mkspecs\modules\qt_lib_widgets.pri:
..\..\..\5.4\mingw491_32\mkspecs\modules\qt_lib_widgets_private.pri:
..\..\..\5.4\mingw491_32\mkspecs\modules\qt_lib_winextras.pri:
..\..\..\5.4\mingw491_32\mkspecs\modules\qt_lib_winextras_private.pri:
..\..\..\5.4\mingw491_32\mkspecs\modules\qt_lib_xml.pri:
..\..\..\5.4\mingw491_32\mkspecs\modules\qt_lib_xml_private.pri:
..\..\..\5.4\mingw491_32\mkspecs\modules\qt_lib_xmlpatterns.pri:
..\..\..\5.4\mingw491_32\mkspecs\modules\qt_lib_xmlpatterns_private.pri:
..\..\..\5.4\mingw491_32\mkspecs\features\qt_functions.prf:
..\..\..\5.4\mingw491_32\mkspecs\features\qt_config.prf:
..\..\..\5.4\mingw491_32\mkspecs\features\win32\qt_config.prf:
..\..\..\5.4\mingw491_32\mkspecs\win32-g++\qmake.conf:
..\..\..\5.4\mingw491_32\mkspecs\features\spec_post.prf:
..\..\..\5.4\mingw491_32\mkspecs\features\exclusive_builds.prf:
..\..\..\5.4\mingw491_32\mkspecs\features\default_pre.prf:
..\..\..\5.4\mingw491_32\mkspecs\features\win32\default_pre.prf:
..\..\..\5.4\mingw491_32\mkspecs\features\resolve_config.prf:
..\..\..\5.4\mingw491_32\mkspecs\features\exclusive_builds_post.prf:
..\..\..\5.4\mingw491_32\mkspecs\features\default_post.prf:
..\..\..\5.4\mingw491_32\mkspecs\features\win32\rtti.prf:
..\..\..\5.4\mingw491_32\mkspecs\features\precompile_header.prf:
..\..\..\5.4\mingw491_32\mkspecs\features\warn_on.prf:
..\..\..\5.4\mingw491_32\mkspecs\features\win32\windows.prf:
..\..\..\5.4\mingw491_32\mkspecs\features\testcase_targets.prf:
..\..\..\5.4\mingw491_32\mkspecs\features\exceptions.prf:
..\..\..\5.4\mingw491_32\mkspecs\features\yacc.prf:
..\..\..\5.4\mingw491_32\mkspecs\features\lex.prf:
SMART_Build.pro:
qmake: FORCE
	@$(QMAKE) -spec win32-g++ CONFIG+=debug -o Makefile SMART_Build.pro

qmake_all: sub-PCC-qmake_all sub-Flasher-qmake_all sub-BRS-qmake_all sub-Emokit-qmake_all sub-BCI-qmake_all FORCE

make_first: sub-PCC-make_first sub-Flasher-make_first sub-BRS-make_first sub-Emokit-make_first sub-BCI-make_first FORCE
all: sub-PCC-all sub-Flasher-all sub-BRS-all sub-Emokit-all sub-BCI-all FORCE
clean: sub-PCC-clean sub-Flasher-clean sub-BRS-clean sub-Emokit-clean sub-BCI-clean FORCE
distclean: sub-PCC-distclean sub-Flasher-distclean sub-BRS-distclean sub-Emokit-distclean sub-BCI-distclean FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-PCC-install_subtargets sub-Flasher-install_subtargets sub-BRS-install_subtargets sub-Emokit-install_subtargets sub-BCI-install_subtargets FORCE
uninstall_subtargets: sub-PCC-uninstall_subtargets sub-Flasher-uninstall_subtargets sub-BRS-uninstall_subtargets sub-Emokit-uninstall_subtargets sub-BCI-uninstall_subtargets FORCE

sub-PCC-debug:
	@if not exist PCC\ mkdir PCC\ & if not exist PCC\ exit 1
	cd PCC\ && ( if not exist Makefile $(QMAKE) C:\Qt\workspace\SMART_Software\SMART_Build\PCC\PCC.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile debug
sub-Flasher-debug:
	@if not exist Flasher\ mkdir Flasher\ & if not exist Flasher\ exit 1
	cd Flasher\ && ( if not exist Makefile $(QMAKE) C:\Qt\workspace\SMART_Software\SMART_Build\Flasher\Flasher.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile debug
sub-BRS-debug:
	@if not exist BRS\ mkdir BRS\ & if not exist BRS\ exit 1
	cd BRS\ && ( if not exist Makefile $(QMAKE) C:\Qt\workspace\SMART_Software\SMART_Build\BRS\BRS.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile debug
sub-Emokit-debug:
	@if not exist Emokit\ mkdir Emokit\ & if not exist Emokit\ exit 1
	cd Emokit\ && ( if not exist Makefile $(QMAKE) C:\Qt\workspace\SMART_Software\SMART_Build\Emokit\Emokit.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile debug
sub-BCI-debug:
	@if not exist BCI\ mkdir BCI\ & if not exist BCI\ exit 1
	cd BCI\ && ( if not exist Makefile $(QMAKE) C:\Qt\workspace\SMART_Software\SMART_Build\BCI\BCI.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile debug
debug: sub-PCC-debug sub-Flasher-debug sub-BRS-debug sub-Emokit-debug sub-BCI-debug

sub-PCC-release:
	@if not exist PCC\ mkdir PCC\ & if not exist PCC\ exit 1
	cd PCC\ && ( if not exist Makefile $(QMAKE) C:\Qt\workspace\SMART_Software\SMART_Build\PCC\PCC.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile release
sub-Flasher-release:
	@if not exist Flasher\ mkdir Flasher\ & if not exist Flasher\ exit 1
	cd Flasher\ && ( if not exist Makefile $(QMAKE) C:\Qt\workspace\SMART_Software\SMART_Build\Flasher\Flasher.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile release
sub-BRS-release:
	@if not exist BRS\ mkdir BRS\ & if not exist BRS\ exit 1
	cd BRS\ && ( if not exist Makefile $(QMAKE) C:\Qt\workspace\SMART_Software\SMART_Build\BRS\BRS.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile release
sub-Emokit-release:
	@if not exist Emokit\ mkdir Emokit\ & if not exist Emokit\ exit 1
	cd Emokit\ && ( if not exist Makefile $(QMAKE) C:\Qt\workspace\SMART_Software\SMART_Build\Emokit\Emokit.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile release
sub-BCI-release:
	@if not exist BCI\ mkdir BCI\ & if not exist BCI\ exit 1
	cd BCI\ && ( if not exist Makefile $(QMAKE) C:\Qt\workspace\SMART_Software\SMART_Build\BCI\BCI.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile release
release: sub-PCC-release sub-Flasher-release sub-BRS-release sub-Emokit-release sub-BCI-release

sub-PCC-check:
	@if not exist PCC\ mkdir PCC\ & if not exist PCC\ exit 1
	cd PCC\ && ( if not exist Makefile $(QMAKE) C:\Qt\workspace\SMART_Software\SMART_Build\PCC\PCC.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile check
sub-Flasher-check:
	@if not exist Flasher\ mkdir Flasher\ & if not exist Flasher\ exit 1
	cd Flasher\ && ( if not exist Makefile $(QMAKE) C:\Qt\workspace\SMART_Software\SMART_Build\Flasher\Flasher.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile check
sub-BRS-check:
	@if not exist BRS\ mkdir BRS\ & if not exist BRS\ exit 1
	cd BRS\ && ( if not exist Makefile $(QMAKE) C:\Qt\workspace\SMART_Software\SMART_Build\BRS\BRS.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile check
sub-Emokit-check:
	@if not exist Emokit\ mkdir Emokit\ & if not exist Emokit\ exit 1
	cd Emokit\ && ( if not exist Makefile $(QMAKE) C:\Qt\workspace\SMART_Software\SMART_Build\Emokit\Emokit.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile check
sub-BCI-check:
	@if not exist BCI\ mkdir BCI\ & if not exist BCI\ exit 1
	cd BCI\ && ( if not exist Makefile $(QMAKE) C:\Qt\workspace\SMART_Software\SMART_Build\BCI\BCI.pro -spec win32-g++ CONFIG+=debug -o Makefile ) && $(MAKE) -f Makefile check
check: sub-PCC-check sub-Flasher-check sub-BRS-check sub-Emokit-check sub-BCI-check
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

