// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: seniordesign.proto

#ifndef PROTOBUF_seniordesign_2eproto__INCLUDED
#define PROTOBUF_seniordesign_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace seniordesign {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_seniordesign_2eproto();
void protobuf_AssignDesc_seniordesign_2eproto();
void protobuf_ShutdownFile_seniordesign_2eproto();

class ProcessingAck;
class ProcessingResults;

enum Direction {
  NEUTRAL = 0,
  FORWARD = 1,
  BACKWARD = 2,
  LEFT = 3,
  RIGHT = 4,
  Direction_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  Direction_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool Direction_IsValid(int value);
const Direction Direction_MIN = NEUTRAL;
const Direction Direction_MAX = RIGHT;
const int Direction_ARRAYSIZE = Direction_MAX + 1;

const ::google::protobuf::EnumDescriptor* Direction_descriptor();
inline const ::std::string& Direction_Name(Direction value) {
  return ::google::protobuf::internal::NameOfEnum(
    Direction_descriptor(), value);
}
inline bool Direction_Parse(
    const ::std::string& name, Direction* value) {
  return ::google::protobuf::internal::ParseNamedEnum<Direction>(
    Direction_descriptor(), name, value);
}
// ===================================================================

class ProcessingResults : public ::google::protobuf::Message {
 public:
  ProcessingResults();
  virtual ~ProcessingResults();

  ProcessingResults(const ProcessingResults& from);

  inline ProcessingResults& operator=(const ProcessingResults& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ProcessingResults& default_instance();

  void Swap(ProcessingResults* other);

  // implements Message ----------------------------------------------

  inline ProcessingResults* New() const { return New(NULL); }

  ProcessingResults* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ProcessingResults& from);
  void MergeFrom(const ProcessingResults& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ProcessingResults* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .seniordesign.Direction direction = 1;
  void clear_direction();
  static const int kDirectionFieldNumber = 1;
  ::seniordesign::Direction direction() const;
  void set_direction(::seniordesign::Direction value);

  // optional double confidence = 2;
  void clear_confidence();
  static const int kConfidenceFieldNumber = 2;
  double confidence() const;
  void set_confidence(double value);

  // @@protoc_insertion_point(class_scope:seniordesign.ProcessingResults)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  double confidence_;
  int direction_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_seniordesign_2eproto();
  friend void protobuf_AssignDesc_seniordesign_2eproto();
  friend void protobuf_ShutdownFile_seniordesign_2eproto();

  void InitAsDefaultInstance();
  static ProcessingResults* default_instance_;
};
// -------------------------------------------------------------------

class ProcessingAck : public ::google::protobuf::Message {
 public:
  ProcessingAck();
  virtual ~ProcessingAck();

  ProcessingAck(const ProcessingAck& from);

  inline ProcessingAck& operator=(const ProcessingAck& from) {
    CopyFrom(from);
    return *this;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ProcessingAck& default_instance();

  void Swap(ProcessingAck* other);

  // implements Message ----------------------------------------------

  inline ProcessingAck* New() const { return New(NULL); }

  ProcessingAck* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ProcessingAck& from);
  void MergeFrom(const ProcessingAck& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ProcessingAck* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional uint64 timestamp = 1;
  void clear_timestamp();
  static const int kTimestampFieldNumber = 1;
  ::google::protobuf::uint64 timestamp() const;
  void set_timestamp(::google::protobuf::uint64 value);

  // @@protoc_insertion_point(class_scope:seniordesign.ProcessingAck)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  bool _is_default_instance_;
  ::google::protobuf::uint64 timestamp_;
  mutable int _cached_size_;
  friend void  protobuf_AddDesc_seniordesign_2eproto();
  friend void protobuf_AssignDesc_seniordesign_2eproto();
  friend void protobuf_ShutdownFile_seniordesign_2eproto();

  void InitAsDefaultInstance();
  static ProcessingAck* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// ProcessingResults

// optional .seniordesign.Direction direction = 1;
inline void ProcessingResults::clear_direction() {
  direction_ = 0;
}
inline ::seniordesign::Direction ProcessingResults::direction() const {
  // @@protoc_insertion_point(field_get:seniordesign.ProcessingResults.direction)
  return static_cast< ::seniordesign::Direction >(direction_);
}
inline void ProcessingResults::set_direction(::seniordesign::Direction value) {
  
  direction_ = value;
  // @@protoc_insertion_point(field_set:seniordesign.ProcessingResults.direction)
}

// optional double confidence = 2;
inline void ProcessingResults::clear_confidence() {
  confidence_ = 0;
}
inline double ProcessingResults::confidence() const {
  // @@protoc_insertion_point(field_get:seniordesign.ProcessingResults.confidence)
  return confidence_;
}
inline void ProcessingResults::set_confidence(double value) {
  
  confidence_ = value;
  // @@protoc_insertion_point(field_set:seniordesign.ProcessingResults.confidence)
}

// -------------------------------------------------------------------

// ProcessingAck

// optional uint64 timestamp = 1;
inline void ProcessingAck::clear_timestamp() {
  timestamp_ = GOOGLE_ULONGLONG(0);
}
inline ::google::protobuf::uint64 ProcessingAck::timestamp() const {
  // @@protoc_insertion_point(field_get:seniordesign.ProcessingAck.timestamp)
  return timestamp_;
}
inline void ProcessingAck::set_timestamp(::google::protobuf::uint64 value) {
  
  timestamp_ = value;
  // @@protoc_insertion_point(field_set:seniordesign.ProcessingAck.timestamp)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace seniordesign

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::seniordesign::Direction> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::seniordesign::Direction>() {
  return ::seniordesign::Direction_descriptor();
}

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_seniordesign_2eproto__INCLUDED
